[package]
name = "storage"
version = "0.1.0"
authors = ["Josh <tarv360@gmail.com>"]
edition = "2018"

[dependencies]
take_mut = "0.2"
derive_deref = "1"
cbc = { version = "0.4.0", package = "crossbeam-channel" }
